import pandas as pd
import matplotlib.pyplot as plt

# Load data from the CSV file generated by your Flask application
# Update this path with the correct file path
blood_test_csv = 'uploads\\blood_report_blood_test.csv'

# Load the CSV data
df_blood_test = pd.read_csv(blood_test_csv)

# List of elements to create bar charts for
elements = ['Hemoglobin', 'White_Blood_Cell_Count', 'Total_Red_Blood_cell_Count', 'Platelet Count']

# Function to create and display a bar chart for a specific element
def create_bar_chart(data, title, x_label, y_label):
    plt.figure()
    plt.hist(data, bins=20, alpha=0.7, rwidth=0.85, color='blue', edgecolor='black')
    plt.xlabel(x_label)
    plt.ylabel(y_label)
    plt.title(title)
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.show()

# Create and display bar charts for each element
for element in elements:
    data = df_blood_test[element]
    title = f'{element} Distribution (Blood Test)'
    x_label = f'{element} Range'
    y_label = 'Frequency'
    create_bar_chart(data, title, x_label, y_label)